language:  generic

notifications:
  slack:
    rooms:
      - apacheexpress:9z2IfvxZfENp0TFmiYCgyUKz

matrix:
    include:
        - os:   Linux
          dist: trusty
          env:  MOD_SWIFT="https://github.com/modswift/mod_swift/archive/0.9.0.tar.gz" SWIFT_SNAPSHOT_NAME="https://swift.org/builds/swift-4.2.4-release/ubuntu1404/swift-4.2.4-RELEASE/swift-4.2.4-RELEASE-ubuntu14.04.tar.gz"
          sudo: required
        - os:   Linux
          dist: trusty
          env:  MOD_SWIFT="https://github.com/modswift/mod_swift/archive/0.9.0.tar.gz" SWIFT_SNAPSHOT_NAME="https://swift.org/builds/swift-5.0-release/ubuntu1404/swift-5.0-RELEASE/swift-5.0-RELEASE-ubuntu14.04.tar.gz"
          sudo: required
        - os:   osx
          osx_image: xcode10.2

before_install:
    - ./.travis.d/before-install.sh

install:
    - ./.travis.d/install.sh

script:
    - export PATH="$HOME/usr/bin:$PATH"
    - export SWIFTENV_ROOT="$HOME/.swiftenv"
    - export PATH="${SWIFTENV_ROOT}/bin:${SWIFTENV_ROOT}/shims:$PATH"
    - swift build -c release
    - swift build -c debug
